name: "Publish CML dockers"

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  TEST_GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }} 
  TEST_GITHUB_REPO: https://github.com/iterative/cml_qa_tests_dummy
  TEST_GITHUB_SHA: 62edc8b3f46a60b3fe1e5c08fd3e0046d350ee29
  TEST_GITLAB_TOKEN: ${{ secrets.TEST_GITLAB_TOKEN }}
  TEST_GITLAB_REPO: https://gitlab.com/iterative.ai/cml_qa_tests_dummy
  TEST_GITLAB_SHA: c4c13286e78dc252dd2611f31a755f10d343fbd4
  TEST_BBCLOUD_TOKEN: ${{ secrets.TEST_BBCLOUD_TOKEN }}
  TEST_BBCLOUD_REPO:  https://bitbucket.org/iterative-ai/cml-qa-tests-dummy
  TEST_BBCLOUD_SHA: 8119698b09994844a6803d5380cc370e0d0ffc6a

jobs:
  # deploy-runner:
  #   runs-on: [ubuntu-latest]

  #   steps:
  #     - uses: hashicorp/setup-terraform@v1
  #       with:
  #         terraform_version: 0.14.3

  #     - uses: actions/checkout@v2

  #     - name: deploy
  #       shell: bash
  #       env:
  #         repo_token: ${{ secrets.repo_token }} 
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #         AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #         AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #         AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #       run: |
  #         npm ci
  #         sudo npm link
  #         cml-runner \
  #         --cloud=azure \
  #         --cloud-region=us-west \
  #         --cloud-type=Standard_A1_v2 \
  #         --labels=cml-runner \
  #         --idle-timeout=0
          
  test_and_deploy:
    #needs: deploy-runner
    #runs-on: [self-hosted,cml-runner]
    #runs-on: [ubuntu-latest]
    runs-on: [self-hosted,tf2]

    steps:
    - uses: actions/checkout@v2

    - name: "npm ci"
      run: npm ci

    - name: "lint"
      run: npm run lint

    - name: "tests"
      run: |
        sudo update-alternatives --install /usr/bin/python python $(which python3) 10
        sudo apt-get update && sudo apt-get install -y python-pip python3-pip 
        sudo pip install --upgrade pip
        sudo pip install --upgrade setuptools
        sudo pip install tensorboard

        echo 'hello world azure' > report.md
        cml-send-comment report.md
